const ESTADOS_RESERVA = Object.freeze({
  PENDIENTE: 'PENDIENTE',
  CONFIRMADA: 'CONFIRMADA',
  CANCELADA: 'CANCELADA',
});

const ESTADOS_RESERVA_ACTIVOS = Object.freeze([
  ESTADOS_RESERVA.PENDIENTE,
  ESTADOS_RESERVA.CONFIRMADA,
]);

module.exports = {
  ESTADOS_RESERVA,
  ESTADOS_RESERVA_ACTIVOS,
};
